# Generated by Django 4.2.7 on 2024-01-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicDesignCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=0)),
                ('Name', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('Date', models.DateField()),
                ('image_cover', models.ImageField(upload_to='media')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
