# Generated by Django 4.2.7 on 2024-02-06 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphicdesigncard',
            name='image_cover',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='graphicdesigncard',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
