# Generated by Django 4.2.7 on 2024-02-10 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_graphicdesigncard_image_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalArtCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
                ('Name', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('Date', models.DateTimeField()),
                ('Image_cover', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
                ('Name', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('Date', models.DateTimeField()),
                ('Image_cover', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='WebDesignCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
                ('Name', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('Date', models.DateField()),
                ('Image_cover', models.ImageField(upload_to='media/')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
