# Generated by Django 4.2.7 on 2024-02-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_digitalartcard_niche_webdesigncard'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalartcard',
            name='url_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='graphicdesigncard',
            name='url_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='niche',
            name='url_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='webdesigncard',
            name='url_link',
            field=models.URLField(default=''),
        ),
    ]
